### ISSUE TITLE
Update documented support for microphone input

### ISSUE THREAD

**Issue by jpweeks** [charisma-ai/charisma-sdk-js#23]
The SpeechRecognition API is now supported by all major browsers except Firefox – https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#browser_compatibility

The readme / docs should be updated to reflect current browser compatibility (currently lists Chrome as the only supported browser). Maybe just linking to the compatibility table would be better than updating browsers in the readme.

**Comment by bensalilijames** [comment]
Many thanks @jpweeks, the README now points to the compatibility table as suggested! Closed in [2be35a9](https://github.com/charisma-ai/charisma-sdk-js/commit/2be35a9dbcd2186fa8d8e22a0c6c45224cc48ed8).
