### ISSUE TITLE
create a demo using direct to deepgram

### ISSUE THREAD

**Issue by John-A-J** [charisma-ai/charisma-sdk-js#44]
major version release

plan part 2 https://www.notion.so/charisma-ai/Audio-renovation-plan-98d03731f3674109901c7a152ee5d478

**Comment by John-A-J** [comment]
We need some sort of audio manager that manages an audio context and has methods for different jobs

play audio
play character speech (with/without interruption ? Needed?)
turn character voices on/off
turn background audio on/off
stop all audio
start microphone input; send STT audio
stop microphone input; stop STT stream. (background audio resumes or too hard?)

**Comment by samuelbeard** [comment]
- [ ] Add their custom story id and key
- [ ] Well commented
- [ ] Deployed and accessible for testing
